spring:
    datasource:
        driver-class-name : com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://192.12.132.42:3306/test?characterEncoding=utf-8&autoReconnect=true
        username: root
        password: baidu@123
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.entity
    configuration:
        map-underscore-to-camel-case: true